In [87]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [88]:
df =pd.read_csv("insurance_data.csv")

In [89]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [90]:
df.shape

(28, 3)

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(df[['age','affordibility']],df.bought_insurance, test_size=0.2,random_state=25)


In [92]:
len(X_test)

6

In [93]:
len(X_train)

22

In [94]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [12]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [95]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='one', bias_initializer='zeros')
])
model.compile(optimizer ='adam',
             loss='binary_crossentropy',
            metrics=['accuracy'] )
model.fit(X_train_scaled,y_train,epochs=500)

C:\Users\03abd\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss

In [96]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step - accuracy: 0.6667 - loss: 0.6210


[0.621041476726532, 0.6666666865348816]

In [10]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[0.66075516],
       [0.60847205],
       [0.451497  ],
       [0.62685424],
       [0.66423655],
       [0.68474233]], dtype=float32)

In [11]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [35]:
coaf,intercept=model.get_weights()
coaf,intercept

(array([[0.7785071 ],
        [0.69779867]], dtype=float32),
 array([-0.39703578], dtype=float32))

In [19]:
## implemention tation of this from scratch innbasic pyhton


In [97]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))

In [98]:
sigmoid(9)

0.9998766054240137

In [99]:
def prediction_function(age,affordibility):
    weighted_sum=coaf[0]*age+coaf[1]*affordibility+intercept
    return sigmoid(  weighted_sum)

In [100]:
prediction_function(0.47,	1)

C:\Users\03abd\AppData\Local\Temp\ipykernel_16796\1356804808.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.6607551440227616

In [101]:
## GRADIANT DESENT FROM SCRATCH 
import numpy as np ##implementaton of absolute_mean_error

y_predicted = np.array([1,1,0,0,1])
y_true= np.array([0.30,0.7,1,0,0.5])

In [102]:
eplison = 1e-15

In [103]:
y_predicted_new= [max(i,eplison)for i in y_predicted]

In [104]:
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [105]:
y_predicted_new = [min(i,1-eplison)for i in y_predicted_new]

In [106]:
y_predicted_new 

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [107]:
y_predicted_new = np.array(y_predicted_new)

In [108]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [109]:
def log_loss(y_true,y_predicted):
    eplison = 1e-15
    y_predicted_new= [max(i,eplison)for i in y_predicted]
    y_predicted_new = [min(i,1-eplison)for i in y_predicted_new]
    y_predicted_new =np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [110]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))    

array([0.99999386, 0.5       , 0.73105858])

In [111]:

class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0
    
    def fit(self, X, y, epochs, loss_threshold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_threshold)

    def predict(self, X_test):
        weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
        return self.sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age, affordibility, y_true, epochs, loss_threshold):
        w1 = self.w1  # Initializing weights
        w2 = self.w2  # Initializing weights
        bias = self.bias  # Initializing bias
        rate = 0.5  # Learning rate
        n = len(age)  # Number of samples

        for i in range(epochs):
            # Calculate the weighted sum and apply the sigmoid function
            weighted_sum = w1 * age + w2 * affordibility + bias
            y_predicted = self.sigmoid_numpy(weighted_sum)

            # Calculate the loss (log loss)
            loss = self.log_loss(y_true, y_predicted)

            # Calculate gradients
            w1d = (1 / n) * np.dot(np.transpose(age), (y_predicted - y_true))
            w2d = (1 / n) * np.dot(np.transpose(affordability), (y_predicted - y_true))
            bias_d = np.mean(y_predicted - y_true)

            # Update weights and bias
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d

            # Print the progress
            print(f'Epoch: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}')
            
            if loss <= loss_threshold:
                break

        return w1, w2, bias

In [39]:
coaf,intercept

(array([[0.7785072 ],
        [0.69779867]], dtype=float32),
 array([-0.39703578], dtype=float32))

In [112]:
## implementing the NN from python 
customModel= myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_threshold=0.4631)

AttributeError: 'myNN' object has no attribute 'sigmoid_numpy'

In [ ]:
customModel.predict(X_train_scaled)


In [82]:
print(X_train_scaled.columns)

Index(['age', 'affordibility'], dtype='object')
